name: 'Merge coverage reports'
author: 'selfagency'
description: 'Merge Istanbul coverage reports'
branding:
  icon: 'git-merge'
  color: 'green'
inputs:
  source:
    description: 'Path to source code'
    required: true
  coverage-reports:
    description: 'Path to coverage reports'
    required: true
  output-folder:
    description: 'Where to output merged reports'
    required: true
  formats:
    description: 'Comma-separated list of formats to output'
    required: false
  artifacts:
    description: 'Whether to create artifacts'
    required: false
    default: 'true'
outputs:
  report:
    description: 'Coverage report'
    value: ${{ steps.merge-coverage.outputs.report }}
  json-summary:
    description: 'JSON coverage summary'
    value: ${{ steps.merge-coverage.outputs.json }}
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: 20

    - name: Configure reporters
      id: configure-reporters
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
      env:
        INPUT_FORMATS: ${{ inputs.formats }}
      with:
        script: |
          const formats = process.env.INPUT_FORMATS || '';
          const reporters = formats
            .split(',')
            .map(r => r.trim())
            .filter(r => /^[a-z][a-z0-9-]*$/i.test(r));
          if (reporters.length) {
            const reporterConfig = reporters.map(r => `--reporter ${r}`).join(' ');
            core.setOutput('reporters', reporterConfig);
          }

    - name: Collect coverage reports
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
      env:
        COVERAGE_REPORTS: ${{ inputs.coverage-reports }}
        WORKSPACE: ${{ github.workspace }}
      with:
        script: |
          const { readdir, copyFile, mkdir } = require('fs').promises;
          const path = require('path');

          const coverageDir = path.join(process.env.WORKSPACE, 'coverage');
          await mkdir(coverageDir, { recursive: true });

          const reports = await readdir(process.env.COVERAGE_REPORTS, { withFileTypes: true });

          const reportDirs = reports.filter(d => d.isDirectory()).map(d => d.name);
          for (const dir of reportDirs) {
            await copyFile(
              path.join(process.env.COVERAGE_REPORTS, dir, 'coverage-final.json'),
              path.join(coverageDir, `${dir}.json`)
            );
          }

          const reportFiles = reports.filter(d => d.isFile() && d.name.endsWith('.json')).map(d => d.name);
          for (const file of reportFiles) {
            await copyFile(
              path.join(process.env.COVERAGE_REPORTS, file),
              path.join(coverageDir, file)
            );
          }

    - name: Merge coverage
      shell: bash
      env:
        WORKSPACE: ${{ github.workspace }}
      run: |
        npx nyc merge "${WORKSPACE}/coverage" "${WORKSPACE}/coverage/coverage-final.json"

    - name: Output coverage report
      id: merge-coverage
      shell: bash
      working-directory: ${{ inputs.source }}
      env:
        WORKSPACE: ${{ github.workspace }}
        OUTPUT_FOLDER: ${{ inputs.output-folder }}
        REPORTERS: ${{ steps.configure-reporters.outputs.reporters }}
      run: |
        npx nyc report -t "${WORKSPACE}/coverage" --reporter text --reporter json --reporter json-summary ${REPORTERS} --report-dir "${OUTPUT_FOLDER}" | tee "${OUTPUT_FOLDER}/coverage-final.txt"

        {
          echo "report<<COVERAGE_REPORT_EOF"
          cat "${OUTPUT_FOLDER}/coverage-final.txt"
          echo "COVERAGE_REPORT_EOF"
        } >> "$GITHUB_OUTPUT"

        report=$(cat "${OUTPUT_FOLDER}/coverage-final.txt")
        report="${report//'%'/'%25'}"
        report="${report//$'\n'/'%0A'}"
        report="${report//$'\r'/'%0D'}"
        echo "::notice::Code Coverage Report%0A%0A${report}"

        {
          echo "json<<COVERAGE_JSON_EOF"
          cat "${OUTPUT_FOLDER}/coverage-summary.json"
          echo "COVERAGE_JSON_EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Upload coverage reports
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      if: ${{ inputs.artifacts == 'true' }}
      with:
        name: coverage-reports
        path: |
          ${{ inputs.output-folder }}
          ${{ github.workspace }}/coverage
